name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: codinggroot/easy-schedule-poc
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch Docker image with caching
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --cache-from=type=registry,ref=${IMAGE_NAME}:cache \
            --cache-to=type=registry,ref=${IMAGE_NAME}:cache,mode=max \
            -f Dockerfile.prod \
            -t ${IMAGE_NAME}:${IMAGE_TAG} \
            -t ${IMAGE_NAME}:latest \
            --push .

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE_NAME: codinggroot/easy-schedule-poc
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull ${{ env.IMAGE_NAME }}:latest
            echo "1. Stopping and removing existing container..."
            docker stop easyshift_prod_poc || true
            docker rm easyshift_prod_poc || true
            echo "2. Starting new container with DB and OAuth config..."
            docker run -d --restart unless-stopped --name easyshift_prod_poc_ -p 8080:${{ secrets.SERVER_PORT }} \
              --add-host=host.docker.internal:host-gateway \
              -e SERVER_PORT="${{ secrets.SERVER_PORT }}" \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_DRIVER="${{ secrets.DB_DRIVER }}" \
              -e DB_DIALECT="${{ secrets.DB_DIALECT }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e APPLICATION_OAUTH_CONFIG="${{ secrets.APPLICATION_OAUTH_CONFIG }}" \
              ${{ env.IMAGE_NAME }}:latest
